name: Google Docker ✅
on:
  repository_dispatch:
    types: [screenshot, copy, click]

jobs:
  browser:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright/python:v1.44.0-jammy
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Playwright
      run: playwright install chromium
    
    - name: Run Browser
      run: python browser.py ${{ github.event.client_payload.event }}
